languageCode = "en-US"
title = "Salva Alcántara"
baseurl = "https://salvalcantara.com/"
theme = "cocoa-eh"
builddrafts = false
canonifyurls = true
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
author = "Salva Alcántara"
disqusshortname = "salvalcantara-com"
googleAnalytics = "UA-106158048-1"
pluralizelisttitles = false
enableEmoji = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[taxonomies]
tag = "tags"
category = "categories"
series = "series"

[permalinks]
blog = "blog/:slug/"

[params]
dateform = "Jan 2, 2006"
dateformfull = "Mon Jan 2 2006 15:04:05 EST"
description = "Salva Alcántara's blog"
copyright = "Copyright © 2017–2020 Salva Alcántara"
logofile = "img/logo.png"
faviconfile = "img/favicon.png"
highlightjs = false
progressively = true
latestpostcount = 5
github = "salvalcantara"
email = "salva@salvalcantara.com"
linkedin = "salvalcantara"
twitter = "salvalcantara"
social_banner = "img/banner.png"
